version: '3.8'
services:
  prycto-client:
    container_name: prycto-client
    image: 'node:14.15.1-alpine'
    command: npx lerna exec 'npm run dev' --scope prycto-client
    depends_on:
      - prycto-server
      - traefik
    ports:
      - '3001:3001'
    user: node
    volumes:
      - './:/home/node/app'
    working_dir: /home/node/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`prycto.localhost`)"
      - "traefik.http.routers.client.entrypoints=web"
      # - "traefik.http.routers.client.tls=true"
      # - "traefik.http.routers.client.tls.certresolver=pryctoClient"

  prycto-server:
    container_name: prycto-server
    image: 'node:14.15.1-alpine'
    command: npx lerna exec 'npm run start:dev' --scope prycto-server
    env_file:
      - ./prycto-server/.env
    depends_on:
      - mongo-prycto
      - redis-prycto
      - traefik
    ports:
      - '3002:3000'
    user: node
    volumes:
      - './:/home/node/app'
    working_dir: /home/node/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`prycto-api.localhost`)"
      - "traefik.http.routers.server.entrypoints=web"
      # - "traefik.http.routers.server.tls=true"
      # - "traefik.http.routers.server.tls.certresolver=pryctoServer"

  mongo-prycto:
    container_name: mongo-prycto
    image: 'mongo:4.4'
    ports:
      - '27019:27017'
    volumes:
      - 'mongo-data-prycto:/data/db'

  redis-prycto:
    container_name: redis-prycto
    image: redis
    restart: always
    ports:
      - 6377:6379
  
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.websecure.address=:443"
      # - "--certificatesResolvers.pryctoClient.acme.email=lionel.bertrand@ymail.com"
      # - "--certificatesResolvers.pryctoClient.acme.storage=acme.json"
      # - "--certificatesResolvers.pryctoClient.acme.httpChallenge.entryPoint=web"
    ports:
      - "80:80"
      # - "443:443"
      # - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  mongo-data-prycto: {}
