export const en = {
  exchanges: "Exchanges",
  exchange: "Exchange",
  logout: "Log out",
  pairs: "Pairs",
  pair: "Pair",
  amount: "Amount",
  averagePrice: "Average price",
  market: "Market",
  investment: "Investment",
  profit: "Profit",
  goal: "Goal",
  loading: "Loading...",
  addExchange: "Add exchange",
  exchangeName: "Exchange name",
  publicKey: "Public key",
  secretKey: "Secret key",
  cancel: "Cancel",
  add: "Add",
  searchPairs: "Search pairs",
  addPosition: "Add position",
  french: "Français",
  english: "English",
  settings: "Settings",
  "settings.email": "Email",
  "settings.password": "Password",
  "settings.confirmPassword": "Confirm password",
  "settings.oldPassword": "Old password",
  save: "Save",
  login: "Login",
  email: "Email",
  password: "Password",
  register: "Register",
  balances: "Balances",
  "balance.available": "Available",
  "balance.locked": "Locked",
  "balance.token": "Token",
  "predicts": "Predictions",
  "predict.description": "Markets prediction for tomorrow",
  "positions.noData": "Add a position",
  "history.title": "History order",
  "history.date": "Date",
  "history.symbol": "Symbol",
  "history.price": "Price",
  "history.amount": "Amount",
  "history.cost": "Cost",
  "history.type": "Type",
  "history.side": "Side",
  "history.status": "Status",
  "history.market": "Market",
  "history.limit": "Limit",
  "history.buy": "Buy",
  "history.sell": "Sell",
  "history.closed": "Executed",
  "history.canceled": "Canceld",
  "gain": "Relatif gain",
  "subTitle": "Easily follow a crypto position",
  "index.descriptif": "Many applications exist to track the NLP of our beloved cryptos. But it is based on the price of a token, regardless of the pair. But when we trade, we need to know the value linked to our position, Prycto comes into play",
};
