export const en = {
  exchanges: "Exchanges",
  exchange: "Exchange",
  logout: "Log out",
  pairs: "Pairs",
  pair: "Pair",
  amount: "Amount",
  averagePrice: "Average price",
  market: "Market",
  investment: "Investment",
  profit: "Profit",
  goal: "Goal",
  loading: "Loading...",
  addExchange: "Add exchange",
  exchangeName: "Exchange name",
  publicKey: "Public key",
  secretKey: "Secret key",
  cancel: "Cancel",
  add: "Add",
  searchPairs: "Search pairs",
  addPosition: "Add position",
  french: "Français",
  english: "English",
  settings: "Settings",
  "settings.email": "Email",
  "settings.password": "Password",
  "settings.confirmPassword": "Confirm password",
  save: "Save",
  login: "Login",
  email: "Email",
  password: "Password",
  register: "Register",
  balances: "Balances",
  "balance.available": "Available",
  "balance.locked": "Locked",
  "balance.token": "Token",
};
