export const fr = {
  exchanges: "Porte-feuilles",
  exchange: "Porte-feuille",
  logout: "Se déconnecter",
  pairs: "Paires",
  pair: "Paire",
  amount: "Quantité",
  averagePrice: "Prix moyen",
  market: "Marché",
  investment: "Investissement",
  profit: "Profit",
  goal: "Objectif",
  loading: "Chargement...",
  addExchange: "Ajouter un porte-feuille",
  exchangeName: "Nom du porte-feuille",
  publicKey: "Clés publique",
  secretKey: "Clés privée",
  cancel: "Annuler",
  add: "Ajouter",
  searchPairs: "Rechercher des paires",
  addPosition: "Ajouter une position",
  french: "Français",
  english: "English",
  settings: "Paramètre",
  "settings.email": "Email",
  "settings.password": "Mot de passe",
  "settings.confirmPassword": "Confirmation du mot de passe",
  "settings.oldPassword": "Ancien mot de passe",
  save: "Enregistrer",
  login: "Se connecter",
  email: "Email",
  password: "Mot de passe",
  register: "Créer un compte",
  balances: "Balances",
  'balance.available': 'Disponible',
  'balance.locked': 'Bloqué',
  "balance.token": "Monnaie",
  "predicts": "Prédictions",
  "predict.description": "Prédiction des cours sur une journée",
  "positions.noData": "Veuillez ajouter une position",
  "history.title": "Historique des ordres",
  "history.date": "Date",
  "history.symbol": "Symbole",
  "history.price": "Prix",
  "history.amount": "Quantité",
  "history.cost": "Coût",
  "history.type": "Type",
  "history.side": "Mouvement",
  "history.status": "Status",
  "history.market": "Marché",
  "history.limit": "Limite",
  "history.buy": "Achat",
  "history.sell": "Vente",
  "history.closed": "Exécuté",
  "history.canceled": "Annulé",
  "gain": "Gain relatif",
  "subTitle": "Suivre une position crypto en toute simplicité",
  "index.descriptif": "Beaucoup d'application existe afin de tracker le PNL de nos cryptos adorées. Mais elles se basent sur le prix d'un token, peu importe la paire. Or quand on fait du trading, on a besoin de connaître la valeur lié à notre position, Prycto rentre en jeux",
};
