export const fr = {
  exchanges: 'Porte-feuilles',
  exchange: 'Porte-feuille',
  logout: "Se déconnecter",
  pairs: 'Paires',
  pair: 'Paire',
  amount: 'Quantité',
  averagePrice: 'Prix moyen',
  market: 'Marché',
  investment: 'Investissement',
  profit: 'Profit',
  goal: 'Objectif',
  loading: 'Chargement...',
  addExchange: 'Ajouter un porte-feuille',
  exchangeName: 'Nom du porte-feuille',
  publicKey: 'Clés publique',
  secretKey: 'Clés privée',
  cancel: 'Annuler',
  add: 'Ajouter',
  searchPairs: 'Rechercher des paires',
  addPosition: 'Ajouter une position',
};